name: Qodana
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/*
      - experiments/*

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request
          fail-threshold: 5
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}